#define DEFAULT_EC_POLL_INTERVAL                3000
#define DEFAULT_CRITICAL_TEMPERATURE            75
#define DEFAULT_CRITICAL_TEMPERATURE_OFFSET     15
#define DEFAULT_LEGACY_TEMPERATURE_BEHAVIOUR    False
#define DEFAULT_READ_WRITE_WORDS                False
